# Generated by Django 6.0.1 on 2026-01-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('minimal', 'Minimal')], default='light', max_length=20)),
                ('background_color', models.CharField(default='#f3f4f6', max_length=20)),
                ('button_color', models.CharField(default='#000000', max_length=20)),
                ('button_text_color', models.CharField(default='#ffffff', max_length=20)),
                ('font_family', models.CharField(default='sans-serif', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
